# docker-compose.yml  (Compose v2 표준: version 키 생략)
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?set-in-env-file}
      MYSQL_USER: ${DB_USER:?set-in-env-file}
      MYSQL_PASSWORD: ${DB_PASSWORD:?set-in-env-file}
      MYSQL_DATABASE: ${DB_NAME:?set-in-env-file}
    networks:
      - app

  redis:
    image: redis:7.0.4
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD:?set-in-env-file}"]
    container_name: redis-container
    hostname: redis_standalone
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?set-in-env-file}
    depends_on:
      - db
    networks:
      - app

  server:
    image: ghcr.io/${GITHUB_ACTOR}/spring-backend:latest
    container_name: spring-backend
    volumes:
      - appdata:/app
    depends_on:
      - db
      - redis
    ports:
      - "7777:7777"
    command:
      - bash
      - -lc
      - |
        /wait-for-it.sh db:3306 -t 15 && \
        java -jar /app.jar
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
